#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ergodox_pretty(KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, TG(2), KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_VOLU, KC_ENT, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_VOLD, KC_MUTE, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_BSLS, KC_LCTL, MO(1), KC_RALT, KC_RGUI, KC_SPC, KC_SPC, KC_RBRC, KC_NO, KC_NO, MO(1), KC_NO, KC_ESC, KC_INS, KC_DEL, KC_HOME, KC_PGUP, KC_SPC, KC_BSPC, KC_END, KC_PGDN, KC_BSPC, KC_ENT),
	[1] = LAYOUT_ergodox_pretty(EE_CLR, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_NO, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_UP, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT, KC_NO, KC_NO, KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LCTL, KC_TRNS, KC_RALT, KC_RGUI, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, RGB_MOD, KC_NO, RGB_TOG, RGB_M_P, KC_NO, KC_NO, RGB_VAD, RGB_VAI, KC_NO, KC_NO, RGB_HUD, RGB_HUI),
	[2] = LAYOUT_ergodox_pretty(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TG(2), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BTN1, KC_MS_U, KC_BTN2, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MS_L, KC_MS_D, KC_MS_R, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};

uint8_t mod_state;
bool esckey_registered;
bool shiftins_registered;
bool ctrlins_registered;
bool process_record_user(uint16_t keycode, keyrecord_t *record) {

    // Store the current modifier state in the variable for later reference
    mod_state = get_mods();
    switch (keycode) {

        // When pressing Ctrl + C, also press esc key
        // Temp fix for intelliSense in VSMac not working with VsVim
        case KC_I:
            if( record->event.pressed )
            {
                if( mod_state & MOD_MASK_CTRL )
                {
                    del_mods( MOD_MASK_CTRL );
                    register_code(KC_ESC);
                    esckey_registered = true;
                    set_mods( mod_state );
                    return true;
                }
            }
            else if ( esckey_registered )
            {
                unregister_code( KC_ESC );
                esckey_registered = false;
                return true;
            }
            break;


        case KC_INS:
            if( record->event.pressed )
            {
                // Shift + Insert as Mac + Paste
                if( mod_state & MOD_MASK_SHIFT )
                {
                    del_mods( MOD_MASK_SHIFT );

                    set_mods( MOD_MASK_GUI );
                    register_code( KC_DOT );

                    set_mods( mod_state );
                    shiftins_registered = true;
                    return false;
                }
                // Ctrl + Insert as Mac + Copy
                else if( mod_state & MOD_MASK_CTRL )
                {
                    del_mods( MOD_MASK_CTRL );

                    set_mods( MOD_MASK_GUI );
                    register_code( KC_I );

                    set_mods( mod_state );
                    ctrlins_registered = true;
                    return false;
                }
            }
            else{
                if( shiftins_registered )
                {
                    unregister_code( KC_DOT );
                    shiftins_registered = false;
                    return false;
                }
                else if( ctrlins_registered )
                {
                    unregister_code( KC_I );
                    ctrlins_registered = false;
                    return false;
                }
            }
            break;
    }
    return true;
};
